const BRANCH_GET_REQUEST = "BRANCH_GET_REQUEST";
const BRANCH_GET_SUCCESS = "BRANCH_GET_SUCCESS";
const BRANCH_GET_FAIL = "BRANCH_GET_FAIL";

const BRANCH_EDIT_REQUEST = "BRANCH_EDIT_REQUEST";
const BRANCH_EDIT_SUCCESS = "BRANCH_EDIT_SUCCESS";
const BRANCH_EDIT_FAIL = "BRANCH_EDIT_FAIL";
const BRANCH_EDIT_RESET = "BRANCH_EDIT_RESET";

export {
  BRANCH_GET_REQUEST,
  BRANCH_GET_SUCCESS,
  BRANCH_GET_FAIL,
  BRANCH_EDIT_REQUEST,
  BRANCH_EDIT_SUCCESS,
  BRANCH_EDIT_FAIL,
  BRANCH_EDIT_RESET,
};
